# Generated by Django 4.2.27 on 2026-06-07 22:20

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blogpage_blog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='content',
            field=wagtail.fields.StreamField([('heading', 2), ('rich_text', 3), ('markdown', 4), ('code', 7), ('image', 8), ('quote', 9), ('alert', 11), ('embed', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'blank': True, 'choices': [('h1', 'H1'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4'), ('h5', 'H5'), ('h6', 'H6')], 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('heading_text', 0), ('size', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {}), 4: ('wagtailmarkdown.blocks.MarkdownBlock', (), {}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('python', 'Python'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('java', 'Java'), ('php', 'PHP'), ('bash', 'Bash'), ('sql', 'SQL'), ('html', 'HTML'), ('css', 'CSS'), ('json', 'JSON')]}), 6: ('wagtail.blocks.TextBlock', (), {}), 7: ('wagtail.blocks.StructBlock', [[('language', 5), ('code', 6)]], {}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 9: ('wagtail.blocks.BlockQuoteBlock', (), {}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('warning', 'Warning'), ('danger', 'Danger'), ('success', 'Success')]}), 11: ('wagtail.blocks.StructBlock', [[('level', 10), ('content', 3)]], {}), 12: ('wagtail.blocks.URLBlock', (), {})}),
        ),
    ]
