# Generated by Django 4.2.27 on 2026-05-28 12:35

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home Page'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.TextField(blank=True, default='Web開発・個人開発・技術学習について発信します'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(default='My Tech Blog', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
