# Generated by Django 4.2.27 on 2026-06-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_footertext_options_blogtitletext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtitletext',
            name='title_text',
            field=models.TextField(blank=True, help_text='ブログタイトルのテキスト(例:マイブログ)', max_length=300),
        ),
    ]
